apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
      - name: project-service
        image: ${ECR_URL}/project-service:latest
        ports:
        - containerPort: 9999
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/taskmanager
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: dev
spec:
  selector:
    app: project-service
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
