apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: ${TARGET_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: ${ECR_URL}/task-service:latest
        ports:
        - containerPort: 9999
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/taskmanager
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: ${TARGET_ENV}
spec:
  selector:
    app: task-service
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
